### ISSUE TITLE
problem with query

### ISSUE THREAD

**Issue by lexand** [osCommerce/oscommerce2#377]
Try to visit site just after installation 
got 

3065 - Expression #1 of ORDER BY clause is not in SELECT list, references column 'osc.p.products_ordered' which is not in SELECT list; this is incompatible with DISTINCT

select distinct p.products_id, pd.products_name from products p, products_description pd where p.products_status = '1' and p.products_ordered > 0 and p.products_id = pd.products_id and pd.language_id = '1' order by p.products_ordered desc, pd.products_name limit 10

MySQL 5.7.11-4

**Comment by oitsuki** [comment]
With mysql 5.7 distinct and order by does'nt work.

**Comment by joniuz** [comment]
Same problem here
MySQL Server version: 5.7.9 
OS: OS X 10.9.5

**Comment by haraldpdl** [comment]
This has been fixed for v2.4 in https://github.com/osCommerce/oscommerce2/commit/253711722fcb9c4aed9b0afb6994322920f02633 and for v2.3 in #419

**Comment by SouthRibbleTech** [comment]
I just download the latest production version from the web site and this issue is still not fixed.
